// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/jobhandsome/microSNS/app/frontend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/send-email-code",
				Handler: SendEmailCodeHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/checkins",
				Handler: UserCheckinsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/integral",
				Handler: UserIntegralHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cate/lists",
				Handler: CateListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/topic/lists",
				Handler: TopicListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/topic/detail",
				Handler: TopicDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/topic/create",
				Handler: TopicCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/topic/delete",
				Handler: TopicDeleteHandler(serverCtx),
			},
		},
	)
}
